---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Mmap
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/scrottie/Sys-Mmap/issues
  repository: https://github.com/scrottie/Sys-Mmap
version: 0.14
